FROM agrigorev/zoomcamp-model:2025

WORKDIR /app

# Copy all files into the container
COPY . .

# Install dependencies
RUN pip install fastapi uvicorn requests

# Expose port for FastAPI
EXPOSE 8000

# Command to start the app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
